merging VampirTrace-5.4.4.1 into the main branch

diff --git a/ompi/contrib/vt/vt/configure b/ompi/contrib/vt/vt/configure
--- a/ompi/contrib/vt/vt/configure
+++ b/ompi/contrib/vt/vt/configure
@@ -735,6 +735,9 @@ am__fastdepCCAS_TRUE
 am__fastdepCCAS_FALSE
 GREP
 EGREP
+ZLIBINCDIR
+ZLIBLIBDIR
+ZLIBLIB
 OTFDIR
 OTFINCDIR
 OTFLIBDIR
@@ -1432,6 +1435,8 @@ Optional Features:
                           enabled
   --disable-dependency-tracking  speeds up one-time build
   --enable-dependency-tracking   do not reject slow dependency extractors
+  --enable-zlib           enable ZLIB trace compression support, default:
+                          enable if found by configure
   --enable-compinst=COMPINSTLIST
                           enable support for compiler instrumentation
                           (gnu,intel,pgi,phat,xl,ftrace), default:
@@ -1448,6 +1453,8 @@ Optional Features:
   --enable-hyb            enable Hybrid (MPI/OpenMP) support, default: enable
                           if MPI-installation found and given compiler
                           supports OpenMP
+  --enable-mpi-io         MPI supports file access, default: yes if found by
+                          configure
   --enable-fmpi-lib       build MPI Fortran support library, default: enable
                           if no MPI Fortran library found by configure
   --enable-memtrace       enable memory tracing support, default: enable if
@@ -1460,6 +1467,14 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-zlib-dir=ZLIBDIR give the path for ZLIB, default: /usr
+  --with-zlib-inc-dir=ZLIBINCDIR
+                          give the path for ZLIB-include files, default:
+                          ZLIB/include
+  --with-zlib-lib-dir=ZLIBLIBDIR
+                          give the path for ZLIB-libraries, default:
+                          ZLIBDIR/lib
+  --with-zlib-lib=ZLIBLIB use given zlib lib, default: -lz
   --with-extern-otf       use external OTF library, default: not set
   --with-extern-otf-dir=OTFDIR
                           give the path for OTF, default: /usr
@@ -1488,7 +1503,7 @@ Optional Packages:
                           LIBERTYDIR/include
   --with-liberty-lib-dir=LIBERTYLIBDIR
                           give the path for LIBERTY-libraries, default:
-                          LIBERTY/lib
+                          LIBERTYDIR/lib
   --with-liberty-lib=LIBERTYLIB
                           use given liberty lib, default: -liberty
   --with-dyninst-dir=DYNIDIR
@@ -1513,8 +1528,6 @@ Optional Packages:
   --with-fmpi-lib         use given fmpi lib
   --with-mpi-status-size  give the value of MPI_STATUS_SIZE, default:
                           automatically by configure
-  --with-mpi-io           MPI supports file access, default: yes if found by
-                          configure
   --with-mpi-native       configure for computer manufacturer MPI
   --with-mpich            configure for MPICH
   --with-mpich2           configure for MPICH2
@@ -8104,11 +8117,302 @@ fi
 
 
 
+	zlib_error="no"
+	check_zlib="yes"
+        force_zlib="no"
+	have_zlib="no"
+
+	ZLIBDIR=
+	ZLIBINCDIR=
+	ZLIBLIBDIR=
+	ZLIBLIB=
+
+	# Check whether --enable-zlib was given.
+if test "${enable_zlib+set}" = set; then
+  enableval=$enable_zlib; if test x"$enableval" = "xyes"; then
+  force_zlib="yes"
+else
+  check_zlib="no"
+fi
+
+fi
+
+
+
+# Check whether --with-zlib-dir was given.
+if test "${with_zlib_dir+set}" = set; then
+  withval=$with_zlib_dir; ZLIBDIR="$withval/"
+fi
+
+
+
+# Check whether --with-zlib-inc-dir was given.
+if test "${with_zlib_inc_dir+set}" = set; then
+  withval=$with_zlib_inc_dir; ZLIBINCDIR="-I$withval/"
+else
+  if test x"$ZLIBDIR" != x; then
+  ZLIBINCDIR="-I$ZLIBDIR"include/
+fi
+
+fi
+
+
+
+# Check whether --with-zlib-lib-dir was given.
+if test "${with_zlib_lib_dir+set}" = set; then
+  withval=$with_zlib_lib_dir; ZLIBLIBDIR="-L$withval/"
+else
+  if test x"$ZLIBDIR" != x; then
+  ZLIBLIBDIR="-L$ZLIBDIR"lib/
+fi
+
+fi
+
+
+
+# Check whether --with-zlib-lib was given.
+if test "${with_zlib_lib+set}" = set; then
+  withval=$with_zlib_lib; ZLIBLIB="$withval"
+fi
+
+
+	if test x"$check_zlib" = "xyes"; then
+
+		sav_CPPFLAGS=$CPPFLAGS
+		CPPFLAGS="$CPPFLAGS $ZLIBINCDIR"
+		if test "${ac_cv_header_zlib_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for zlib.h" >&5
+echo $ECHO_N "checking for zlib.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_zlib_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_zlib_h" >&5
+echo "${ECHO_T}$ac_cv_header_zlib_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking zlib.h usability" >&5
+echo $ECHO_N "checking zlib.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <zlib.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking zlib.h presence" >&5
+echo $ECHO_N "checking zlib.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <zlib.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: zlib.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: zlib.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: zlib.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: zlib.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: zlib.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: zlib.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: zlib.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: zlib.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: zlib.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: zlib.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: zlib.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: zlib.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: zlib.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: zlib.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: zlib.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: zlib.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## -------------------------------- ##
+## Report this to service@vampir.eu ##
+## -------------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for zlib.h" >&5
+echo $ECHO_N "checking for zlib.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_zlib_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_zlib_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_zlib_h" >&5
+echo "${ECHO_T}$ac_cv_header_zlib_h" >&6; }
+
+fi
+if test $ac_cv_header_zlib_h = yes; then
+  :
+else
+
+			{ echo "$as_me:$LINENO: error: no zlib.h found; check path for ZLIB package first..." >&5
+echo "$as_me: error: no zlib.h found; check path for ZLIB package first..." >&6;}
+			zlib_error="yes"
+
+fi
+
+
+		CPPFLAGS=$sav_CPPFLAGS
+
+		if test x"$ZLIBLIB" = x -a x"$zlib_error" = "xno"; then
+
+			sav_LIBS=$LIBS
+			LIBS="$LIBS $ZLIBLIBDIR -lz"
+			{ echo "$as_me:$LINENO: checking whether linking with -lz works" >&5
+echo $ECHO_N "checking whether linking with -lz works... $ECHO_C" >&6; }
+			cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }; ZLIBLIB=-lz
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+			LIBS=$sav_LIBS
+
+fi
+
+
+		if test x"$ZLIBLIB" = x -a x"$zlib_error" = "xno"; then
+
+			{ echo "$as_me:$LINENO: error: no libz found; check path for ZLIB package first..." >&5
+echo "$as_me: error: no libz found; check path for ZLIB package first..." >&6;}
+			zlib_error="yes"
+
+fi
+
+
+		if test x"$ZLIBLIB" != x -a x"$zlib_error" = "xno"; then
+  have_zlib="yes"
+fi
+
+
+		if test x"$force_zlib" = "xyes" -a x"$zlib_error" = "xyes"; then
+  exit 1
+fi
+
+
+fi
+
+
+
+
+
+
+
 	otf_error="no"
 
 	OTFDIR=
 	OTFINCDIR=
 	OTFLIBDIR=
+
+
 
 
 # Check whether --with-extern-otf was given.
@@ -8314,9 +8618,9 @@ fi
 		if test x"$OTFLIB" = x -a "$otf_error" = "no"; then
 
 			sav_LIBS=$LIBS
-			LIBS="$LIBS $OTFLIBDIR -lotf -lz"
-			{ echo "$as_me:$LINENO: checking whether linking with -lotf -lz works" >&5
-echo $ECHO_N "checking whether linking with -lotf -lz works... $ECHO_C" >&6; }
+			LIBS="$LIBS $OTFLIBDIR -lotf $ZLIBLIBDIR $ZLIBLIB"
+			{ echo "$as_me:$LINENO: checking whether linking with -lotf $ZLIBLIBDIR $ZLIBLIB works" >&5
+echo $ECHO_N "checking whether linking with -lotf $ZLIBLIBDIR $ZLIBLIB works... $ECHO_C" >&6; }
 			cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -8351,7 +8655,7 @@ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
        } && test -s conftest$ac_exeext &&
        $as_test_x conftest$ac_exeext; then
   { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }; OTFLIB="-lotf -lz"
+echo "${ECHO_T}yes" >&6; }; OTFLIB="-lotf $ZLIBLIBDIR $ZLIBLIB"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
@@ -8410,17 +8714,34 @@ fi
 		esac
 
 		otf_conf_cmd="$otf_srcdir/configure"
-		otf_conf_args=""
+		if test x"$have_zlib" = "xyes"; then
+
+			if test x"$force_zlib" = "xyes"; then
+  otf_conf_args=--with-zlib
+else
+  otf_conf_args=""
+fi
+
+
+else
+
+			otf_conf_args=--without-zlib
+
+fi
+
 		if test x"$cross_compiling" = "xyes"; then
-  if test ! -z $build; then
+
+			if test ! -z $build; then
   otf_conf_args="$otf_conf_args --build=$build"
 fi
 
-			 if test ! -z $host; then
+			if test ! -z $host; then
   otf_conf_args="$otf_conf_args --host=$host"
 fi
 
+
 fi
+
 
 		otf_conf_args="$otf_conf_args --prefix=\"$prefix\" --exec-prefix=\"$exec_prefix\" --bindir=\"$bindir\" --libdir=\"$libdir\" --includedir=\"$includedir\" --datarootdir=\"$datarootdir\" --datadir=\"$datadir\" --docdir=\"$docdir\" $OTFFLAGS --cache-file=\"/dev/null\" --srcdir=\"$otf_srcdir\""
 
@@ -8436,65 +8757,10 @@ fi
 
 		cd $otf_parent_dir
 
-				sav_LIBS=$LIBS
-		cl="-lz"
-		if test x"$zlib_lib_dir" != x; then
-			cl="-L$zlib_lib_dir $cl"
-		fi
-		LIBS="$LIBS $cl"
-		{ echo "$as_me:$LINENO: checking whether linking with -lz works" >&5
-echo $ECHO_N "checking whether linking with -lz works... $ECHO_C" >&6; }
-		cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-
-int
-main ()
-{
-
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (ac_try="$ac_link"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_link") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest$ac_exeext &&
-       $as_test_x conftest$ac_exeext; then
-  { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }; zlib_lib=-lz
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	{ echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
-      conftest$ac_exeext conftest.$ac_ext
-		LIBS=$sav_LIBS
-
 		OTFINCDIR=
 		OTFLIBDIR=
 		if test x"$OTFLIB" = x; then
-  OTFLIB="-lotf $zlib_lib"
+  OTFLIB="-lotf $ZLIBLIBDIR $ZLIBLIB"
 fi
 
 
@@ -11088,10 +11354,14 @@ fi
 fi
 
 
+	# Check whether --enable-mpi-io was given.
+if test "${enable_mpi_io+set}" = set; then
+  enableval=$enable_mpi_io; if test x"$enableval" = "xyes"; then
+  have_mpio=yes
+else
+  have_mpio=no
+fi
 
-# Check whether --with-mpi-io was given.
-if test "${with_mpi_io+set}" = set; then
-  withval=$with_mpi_io; have_mpio="$withval"
 fi
 
 
@@ -15426,6 +15696,9 @@ am__fastdepCCAS_TRUE!$am__fastdepCCAS_TRUE$ac_delim
 am__fastdepCCAS_FALSE!$am__fastdepCCAS_FALSE$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
+ZLIBINCDIR!$ZLIBINCDIR$ac_delim
+ZLIBLIBDIR!$ZLIBLIBDIR$ac_delim
+ZLIBLIB!$ZLIBLIB$ac_delim
 OTFDIR!$OTFDIR$ac_delim
 OTFINCDIR!$OTFINCDIR$ac_delim
 OTFLIBDIR!$OTFLIBDIR$ac_delim
@@ -15497,9 +15770,6 @@ AMHAVEPAPI_TRUE!$AMHAVEPAPI_TRUE$ac_delim
 AMHAVEPAPI_FALSE!$AMHAVEPAPI_FALSE$ac_delim
 VT_WRAPPER_EXTRA_CFLAGS!$VT_WRAPPER_EXTRA_CFLAGS$ac_delim
 VT_WRAPPER_EXTRA_CXXFLAGS!$VT_WRAPPER_EXTRA_CXXFLAGS$ac_delim
-VT_WRAPPER_EXTRA_FFLAGS!$VT_WRAPPER_EXTRA_FFLAGS$ac_delim
-VT_WRAPPER_EXTRA_FCFLAGS!$VT_WRAPPER_EXTRA_FCFLAGS$ac_delim
-VT_WRAPPER_EXTRA_LDFLAGS!$VT_WRAPPER_EXTRA_LDFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -15541,6 +15811,9 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+VT_WRAPPER_EXTRA_FFLAGS!$VT_WRAPPER_EXTRA_FFLAGS$ac_delim
+VT_WRAPPER_EXTRA_FCFLAGS!$VT_WRAPPER_EXTRA_FCFLAGS$ac_delim
+VT_WRAPPER_EXTRA_LDFLAGS!$VT_WRAPPER_EXTRA_LDFLAGS$ac_delim
 VT_WRAPPER_EXTRA_LIBS!$VT_WRAPPER_EXTRA_LIBS$ac_delim
 VT_WRAPPER_INCDIR!$VT_WRAPPER_INCDIR$ac_delim
 VT_WRAPPER_LIBDIR!$VT_WRAPPER_LIBDIR$ac_delim
@@ -15551,7 +15824,7 @@ LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 8; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 11; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -16222,6 +16495,14 @@ else
 fi
 
 		echo "  Build OTF library and tools:               $answer"
+
+		if test x"$have_zlib" = "xyes"; then
+  answer="yes"
+else
+  answer="no"
+fi
+
+		echo "   ZLIB trace compression support            $answer"
 
 		if test x"$build_mpi" = "xyes"; then
   answer="yes"
