check if VT should link '-lz' in addition to '-lotf' on behalf of OTF

diff --git a/ompi/contrib/vt/vt/configure b/ompi/contrib/vt/vt/configure
--- a/ompi/contrib/vt/vt/configure
+++ b/ompi/contrib/vt/vt/configure
@@ -8436,10 +8436,65 @@ fi
 
 		cd $otf_parent_dir
 
+				sav_LIBS=$LIBS
+		cl="-lz"
+		if test x"$zlib_lib_dir" != x; then
+			cl="-L$zlib_lib_dir $cl"
+		fi
+		LIBS="$LIBS $cl"
+		{ echo "$as_me:$LINENO: checking whether linking with -lz works" >&5
+echo $ECHO_N "checking whether linking with -lz works... $ECHO_C" >&6; }
+		cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  { echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; }; zlib_lib=-lz
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	{ echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+		LIBS=$sav_LIBS
+
 		OTFINCDIR=
 		OTFLIBDIR=
 		if test x"$OTFLIB" = x; then
-  OTFLIB="-lotf -lz"
+  OTFLIB="-lotf $zlib_lib"
 fi
 
 
