Fixes trac:3605: Move VT v5.14.4 changes to v1.7
---svn-pre-commit-ignore-below---

r28494 [[BR]]
Changes to VT:
 * general:
	* incremented version number to 5.14.4
	* fixed Coverity CIDs: 72002, 72099, 72273, 710580, 710664, 710665, 710666
 * VT libs:
	* fixed "incompatible declaration" errors when building against an MPI-3 implementation. Since MPI-3 the C keyword "const" is added to all relevant MPI API parameters (e.g. MPI_Send(void* sendbuf, ...) -> MPI_Send(const void* sendbuf, ...)). Prepending the macro CONST to these parameters which is defined either to "const" (if MPI-3) or to nothing (if MPI-1/2).
	* fixed potential buffer overflow when reading the filter file
	* CUDA tracing:
		* enabled access to CUPTI counters for CUDA tracing via CUPTI
		* enabled GPU memory usage tracing independent of the CUDA API
		* enabled recording of CUDA synchronization and implicit synchronization in blocking CUDA memory copies for CUDA tracing via CUPTI
		* enabled recording of synchronous peer-to-peer CUDA memory copies for CUDA tracing via CUPTI
		* consider CUDA data transfers as not idle for option 'pure_idle'
		* fixed identification of the CUDA device ID for CUDA tracing via CUPTI
		* fixed region filtering for applications using the CUDA runtime API wrapper
 * compiler wrappers: add path to mpi.h to the PDT parser command and preprocessor flags

r28524 [[BR]]
Changes to VT:
	* fixed compiler warnings when compiling for 32-bit
	* MPI wrapper generator scripts:
		* removed non-posix call to length(array)
		* exit scripts if any statement returns a non-true return value (set -e)

This commit was SVN r28545.

The following SVN revision numbers were found above:
  r28494 --> open-mpi/ompi@9a0432632af38efac910d5c86ba5015b888f441c
  r28524 --> open-mpi/ompi@ef0a080028de9f49abc1219eafbfd7701af5636f

The following Trac tickets were found above:
  Ticket 3605 --> https://svn.open-mpi.org/trac/ompi/ticket/3605

diff --git a/ompi/contrib/vt/vt/config/mpigen/mk_fortran_wrapper.sh.in b/ompi/contrib/vt/vt/config/mpigen/mk_fortran_wrapper.sh.in
--- a/ompi/contrib/vt/vt/config/mpigen/mk_fortran_wrapper.sh.in
+++ b/ompi/contrib/vt/vt/config/mpigen/mk_fortran_wrapper.sh.in
@@ -1,8 +1,13 @@
 ##
 # @configure_input@
 #
-# make fortran_wrapper.c
+# make vtlib/vt_fmpiwrap.gen.c
 ##
+
+# exit the script if any statement returns a non-true return value
+set -e
+
+
 
 export SRCDIR=@top_vt_srcdir@/config/mpigen
 
@@ -55,7 +60,8 @@ for s in $src; do
     -e 's/(/,/' \
     -e 's/);//' \
     -e 's/, /,/g' \
-    -e 's/,$//'
+    -e 's/,$//' \
+    -e 's/CONST//g'
 done
 
 cat <<End-of-File >$tmp.c
