Modify make_dist_tarball to conditionally allow it when ''higher'' than expected versions of tools are found.  make_dist_tarball will ''not'' accept lower or higher versions by default (since the goal is exact reproducability, after all), but you can specify the --highok command line switch to allow it.
I'm also removing make_tarball in this commit and will replace it with
a sym link to make_dist_tarball in the next commit.  The script will
default to allowing higher versions of the tools when invoked with an
argv[0] of "make tarball" (i.e., --highok is not necessary, but is
harmless).

diff --git a/contrib/dist/make_dist_tarball b/contrib/dist/make_dist_tarball
--- a/contrib/dist/make_dist_tarball
+++ b/contrib/dist/make_dist_tarball
@@ -10,7 +10,7 @@
 #                         University of Stuttgart.  All rights reserved.
 # Copyright (c) 2004-2005 The Regents of the University of California.
 #                         All rights reserved.
-# Copyright (c) 2008      Cisco Systems, Inc.  All rights reserved.
+# Copyright (c) 2008-2009 Cisco Systems, Inc.  All rights reserved.
 # $COPYRIGHT$
 # 
 # Additional copyrights may follow
@@ -28,6 +28,32 @@ AC_TARGET_VERSION=2.63
 LT_TARGET_VERSION=2.2.6
 
 #
+# Check command line flags
+#
+
+# Default to requiring *exact* versions if we're making distribution
+# tarballs; but higher-than-expected versions are ok for
+# non-distribution tarballs.
+dist_target=distcheck
+if test "`basename $0`" = "make_tarball"; then
+    dist_target=dist
+    highok=1
+else
+    highok=0
+fi
+
+greekonly=0
+while test "$1" != ""; do
+    case $1 in
+        -greekonly) greekonly=1 ;;
+        --greekonly) greekonly=1 ;;
+        -highok) highok=1 ;;
+        --highok) highok=1 ;;
+    esac
+    shift
+done
+
+#
 # First things first -- check that the auto versions that we have are
 # the ones that we want.
 #
@@ -37,10 +63,46 @@ check_gnu_version() {
     target="$2"
 
     ver="`$prog --version | head -n 1 | sed -e's/([^)]*)//g' -e's/[^0-9 .][^ ]* / /g' -e's/ //g'`"
+
+    ver_major=`echo $ver | cut -d. -f1`
+    ver_minor=`echo $ver | cut -d. -f2`
+    ver_release=`echo $ver | cut -d. -f3`
+    if test "$ver_release" = ""; then
+        ver_release=0
+    fi
+
+    target_major=`echo $target | cut -d. -f1`
+    target_minor=`echo $target | cut -d. -f2`
+    target_release=`echo $target | cut -d. -f3`
+    if test "$target_release" = ""; then
+        target_release=0
+    fi
+
+    result=same
     if test "$ver" != "$target"; then 
+        if test "$ver_major" -lt "$target_major"; then
+            result=low
+        elif test "$ver_major" = "$target_major" -a "$ver_minor" -lt "$target_minor"; then
+            result=low
+        elif test "$ver_major" = "$target_major" -a "$ver_minor" = "$target_minor" -a "$ver_release" -lt "$target_release"; then
+            result=low
+        elif test "$ver_major" -gt "$target_major"; then
+            result=high
+        elif test "$ver_major" = "$target_major" -a "$ver_minor" -gt "$target_minor"; then
+            result=high
+        elif test "$ver_major" = "$target_major" -a "$ver_minor" = "$target_minor" -a "$ver_release" -gt "$target_release"; then
+            result=high
+        else
+            result=unknown
+        fi
+    fi
+
+    if test "$result" = "low"; then
         cat <<EOF
-ERROR: Program "$prog" does not have the correct/expected version:
+----------------------------------------------------------------------
+ERROR: Program "$prog" does not have a high enough version:
        Found: $ver
+       Expected: $target
 
 Expected versions:
 m4: $M4_TARGET_VERSION
@@ -50,8 +112,49 @@ Libtool:  $LT_TARGET_VERSION
 
 Either change this script to match the found version, or install
 the correct version of the tools.
+----------------------------------------------------------------------
 EOF
         exit 1
+    fi
+
+    if test "$result" = "high"; then
+        if test "$highok" = "0"; then
+            cat <<EOF
+----------------------------------------------------------------------
+ERROR: Program "$prog" has a higher version than expected:
+       Found: $ver
+       Expected: $target
+
+Expected versions:
+m4: $M4_TARGET_VERSION
+Automake: $AM_TARGET_VERSION
+Autoconf: $AC_TARGET_VERSION
+Libtool:  $LT_TARGET_VERSION
+
+Either change this script to match the found version, or install
+the correct version of the tools.
+----------------------------------------------------------------------
+EOF
+            exit 1
+        else
+            cat <<EOF
+----------------------------------------------------------------------
+WARNING: Program "$prog" has a higher version than expected:
+         Found: $ver
+         Expected: $target
+
+Expected versions:
+m4: $M4_TARGET_VERSION
+Automake: $AM_TARGET_VERSION
+Autoconf: $AC_TARGET_VERSION
+Libtool:  $LT_TARGET_VERSION
+
+This is *usually* ok, but this script is going to sleep for 5 seconds
+to give you the chance to quit before doing anything.
+----------------------------------------------------------------------
+EOF
+            sleep 5
+        fi
     fi
 }
 
@@ -85,13 +188,13 @@ make_tarball() {
     #
     # make tarball
     #
-    echo "*** Running make distcheck..."
+    echo "*** Running make $dist_target..."
     save_LD=$LD_LIBRARY_PATH
     LD_LIBRARY_PATH=
     rm -f success
-    (make distcheck 2>&1 && touch success) | tee dist.out
+    (make $dist_target 2>&1 && touch success) | tee dist.out
     if test ! -f success; then
-        echo "Make dist failed.  Aborting"
+        echo "Make $dist_target failed.  Aborting"
         exit 1
     fi
     rm -f success
@@ -190,7 +293,7 @@ make_tarball
 
 # Now if ! --greekonly, make the non-greek tarball
 
-if test "$1" != "-greekonly" -a "$1" != "--greekonly"; then
+if test "$greekonly" = "0"; then
     echo "*** REMOVING ALL GREEK FROM VERSION NUMBERS!!"
     for file in $version_files; do
         echo " - $file"
